macro(add_sdk_compat_header _source)
    get_filename_component(_name ${_source} NAME)
    set(_src ${REACTOS_SOURCE_DIR}/${_source})
    set(_dst ${REACTOS_BINARY_DIR}/sdk/include/${_name})
    add_custom_command(
        OUTPUT ${_dst}
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_src} ${_dst}
        DEPENDS ${_src})
    list(APPEND SDK_COMPAT_HEADERS ${_dst})
endmacro()

macro(add_sdk_compat_header_path _source _relative_destination)
    set(_src ${REACTOS_SOURCE_DIR}/${_source})
    set(_dst ${REACTOS_BINARY_DIR}/sdk/include/${_relative_destination})
    get_filename_component(_dst_dir ${_dst} DIRECTORY)
    add_custom_command(
        OUTPUT ${_dst}
        COMMAND ${CMAKE_COMMAND} -E make_directory ${_dst_dir}
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${_src} ${_dst}
        DEPENDS ${_src})
    list(APPEND SDK_COMPAT_HEADERS ${_dst})
endmacro()

add_sdk_compat_header(sdk/include/psdk/sdkddkver.h)
add_sdk_compat_header(sdk/include/psdk/winapifamily.h)
add_sdk_compat_header(sdk/include/psdk/winpackagefamily.h)
add_sdk_compat_header(sdk/include/msvctarget.h)
add_sdk_compat_header(sdk/include/ddk/kernelspecs.h)
add_sdk_compat_header(sdk/include/ndk/section_attribs.h)
add_sdk_compat_header(sdk/include/psdk/apiset.h)
add_sdk_compat_header(sdk/include/psdk/apisetcconv.h)
add_sdk_compat_header(sdk/include/psdk/concurrencysal.h)
add_sdk_compat_header(sdk/include/psdk/dontuse.h)
add_sdk_compat_header(sdk/include/psdk/driverspecs.h)
add_sdk_compat_header(sdk/include/psdk/packon.h)
add_sdk_compat_header(sdk/include/psdk/packoff.h)
add_sdk_compat_header(sdk/include/psdk/pshpack1.h)
add_sdk_compat_header(sdk/include/psdk/pshpack2.h)
add_sdk_compat_header(sdk/include/psdk/pshpack4.h)
add_sdk_compat_header(sdk/include/psdk/pshpack8.h)
add_sdk_compat_header(sdk/include/psdk/poppack.h)
add_sdk_compat_header(sdk/include/psdk/wtypesbase.h)
add_sdk_compat_header(sdk/include/vcruntime/excpt.h)
add_sdk_compat_header(sdk/include/vcruntime/gcc_sal.h)
add_sdk_compat_header(sdk/include/vcruntime/intrin.h)
add_sdk_compat_header(sdk/include/vcruntime/intrin0.inl.h)
add_sdk_compat_header(sdk/include/vcruntime/ms_sal.h)
add_sdk_compat_header(sdk/include/vcruntime/_mingw.h)
add_sdk_compat_header(sdk/include/vcruntime/_mingw_mac.h)
add_sdk_compat_header(sdk/include/vcruntime/crtdefs.h)
add_sdk_compat_header(sdk/include/vcruntime/sal.h)
add_sdk_compat_header(sdk/include/vcruntime/setjmp.h)
add_sdk_compat_header(sdk/include/vcruntime/setjmpex.h)
add_sdk_compat_header(sdk/include/vcruntime/vadefs.h)
add_sdk_compat_header(sdk/include/vcruntime/vcruntime.h)
add_sdk_compat_header(sdk/include/ucrt/corecrt.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/gcc_float.h mingw32/gcc_float.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/intrin.h mingw32/intrin.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/intrin_arm.h mingw32/intrin_arm.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/intrin_ppc.h mingw32/intrin_ppc.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/intrin_x86.h mingw32/intrin_x86.h)
add_sdk_compat_header_path(sdk/include/vcruntime/mingw32/intrin_x86_64.h mingw32/intrin_x86_64.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/excpt.h pseh/excpt.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/framebased.h pseh/framebased.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/framebased/internal.h pseh/framebased/internal.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/pseh.h pseh/pseh.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/pseh2.h pseh/pseh2.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/pseh2_64.h pseh/pseh2_64.h)
add_sdk_compat_header_path(sdk/lib/pseh/include/pseh/pseh3.h pseh/pseh3.h)

add_custom_target(sdk_compat_headers ALL DEPENDS ${SDK_COMPAT_HEADERS})

add_subdirectory(asm)
add_subdirectory(dxsdk)
add_subdirectory(ndk/tests)
add_subdirectory(psdk)
add_subdirectory(reactos)
add_subdirectory(wine)
add_subdirectory(xdk)

if(TARGET xdk)
    add_dependencies(xdk sdk_compat_headers)
endif()
