/*
 * PROJECT:     ReactOS VirtIO GPU Miniport
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Minimal 2D VirtIO GPU videoport miniport for QEMU virtio-gpu
 */

#ifndef _VIRTGPU_PCH_
#define _VIRTGPU_PCH_

#include "osdep.h"

#include <dderror.h>
#define __BROKEN__
#include <miniport.h>
#undef __BROKEN__
#include <video.h>
#include <devioctl.h>
#include <stddef.h>

#include "virtio_pci.h"
#include "VirtIO.h"
#include "linux/virtio_config.h"
#include "virtgpu_shared.h"

#define VIRTGPU_TAG 'gtrV'
#define VIRTGPU_VENDOR_ID 0x1AF4
#define VIRTGPU_MODERN_DEVICE_ID 0x1050
#define VIRTGPU_LEGACY_DEVICE_ID_BASE 0x1000
#define VIRTGPU_LEGACY_DEVICE_ID_LAST 0x103F
#define VIRTGPU_DEVICE_ID 16

#define VIRTGPU_RESOURCE_ID 1
#define VIRTGPU_CURSOR_RESOURCE_ID 2
#define VIRTGPU_FIRST_3D_RESOURCE_ID 0x100
#define VIRTGPU_SCANOUT_ID 0
#define VIRTGPU_COMMAND_BUFFER_SIZE 131072
#define VIRTGPU_RESPONSE_OFFSET 65536
#define VIRTGPU_ASYNC_COMMAND_COUNT 64
#define VIRTGPU_ASYNC_COMMAND_SLOT_SIZE 256
#define VIRTGPU_ASYNC_RESPONSE_OFFSET 128
#define VIRTGPU_CURSOR_COMMAND_BUFFER_SIZE 256
#define VIRTGPU_CURSOR_COMMAND_COUNT 8
#define VIRTGPU_CURSOR_WIDTH 64
#define VIRTGPU_CURSOR_HEIGHT 64
#define VIRTGPU_MAX_SHARED_ALLOCATIONS 16
#define VIRTGPU_MAX_ACCESS_RANGES 16
#define VIRTGPU_MAX_VIDEO_MODES 64
#define VIRTGPU_MIN_VIDEO_WIDTH 640
#define VIRTGPU_MIN_VIDEO_HEIGHT 480
#define VIRTGPU_EDID_SIZE 1024
#define VIRTGPU_MAX_CAPSETS VIRTGPU_SHARED_MAX_CAPSETS
#define VIRTGPU_MAX_3D_CONTEXTS 16
#define VIRTGPU_MAX_3D_RESOURCES 64
#define VIRTGPU_MAX_3D_BACKING_SIZE (64 * 1024 * 1024)

#define VIRTGPU_FLAG_FENCE (1 << 0)
#define VIRTGPU_FLAG_INFO_RING_IDX (1 << 1)

#define VIRTGPU_F_VIRGL 0
#define VIRTGPU_F_EDID 1
#define VIRTGPU_F_RESOURCE_UUID 2
#define VIRTGPU_F_RESOURCE_BLOB 3
#define VIRTGPU_F_CONTEXT_INIT 4
#define VIRTGPU_CONTEXT_INIT_CAPSET_ID_MASK 0x000000ff

#define VIRTGPU_CAPSET_VIRGL VIRTGPU_SHARED_CAPSET_VIRGL
#define VIRTGPU_CAPSET_VIRGL2 VIRTGPU_SHARED_CAPSET_VIRGL2
#define VIRTGPU_CAPSET_GFXSTREAM_VULKAN VIRTGPU_SHARED_CAPSET_GFXSTREAM_VULKAN
#define VIRTGPU_CAPSET_VENUS VIRTGPU_SHARED_CAPSET_VENUS
#define VIRTGPU_CAPSET_CROSS_DOMAIN VIRTGPU_SHARED_CAPSET_CROSS_DOMAIN
#define VIRTGPU_CAPSET_DRM VIRTGPU_SHARED_CAPSET_DRM

#define VIRTGPU_BLOB_MEM_GUEST VIRTGPU_SHARED_BLOB_MEM_GUEST
#define VIRTGPU_BLOB_MEM_HOST3D VIRTGPU_SHARED_BLOB_MEM_HOST3D
#define VIRTGPU_BLOB_MEM_HOST3D_GUEST VIRTGPU_SHARED_BLOB_MEM_HOST3D_GUEST

#define VIRTGPU_BLOB_FLAG_USE_MAPPABLE VIRTGPU_SHARED_BLOB_FLAG_USE_MAPPABLE
#define VIRTGPU_BLOB_FLAG_USE_SHAREABLE VIRTGPU_SHARED_BLOB_FLAG_USE_SHAREABLE
#define VIRTGPU_BLOB_FLAG_USE_CROSS_DEVICE VIRTGPU_SHARED_BLOB_FLAG_USE_CROSS_DEVICE
#define VIRTGPU_BLOB_FLAG_USE_MASK \
    (VIRTGPU_BLOB_FLAG_USE_MAPPABLE | \
     VIRTGPU_BLOB_FLAG_USE_SHAREABLE | \
     VIRTGPU_BLOB_FLAG_USE_CROSS_DEVICE)

typedef enum _VIRTGPU_CTRL_TYPE
{
    VIRTGPU_CMD_GET_DISPLAY_INFO = 0x0100,
    VIRTGPU_CMD_RESOURCE_CREATE_2D = 0x0101,
    VIRTGPU_CMD_RESOURCE_UNREF = 0x0102,
    VIRTGPU_CMD_SET_SCANOUT = 0x0103,
    VIRTGPU_CMD_RESOURCE_FLUSH = 0x0104,
    VIRTGPU_CMD_TRANSFER_TO_HOST_2D = 0x0105,
    VIRTGPU_CMD_RESOURCE_ATTACH_BACKING = 0x0106,
    VIRTGPU_CMD_RESOURCE_DETACH_BACKING = 0x0107,
    VIRTGPU_CMD_GET_CAPSET_INFO = 0x0108,
    VIRTGPU_CMD_GET_CAPSET = 0x0109,
    VIRTGPU_CMD_GET_EDID = 0x010A,
    VIRTGPU_CMD_RESOURCE_ASSIGN_UUID = 0x010B,
    VIRTGPU_CMD_RESOURCE_CREATE_BLOB = 0x010C,
    VIRTGPU_CMD_SET_SCANOUT_BLOB = 0x010D,
    VIRTGPU_CMD_CTX_CREATE = 0x0200,
    VIRTGPU_CMD_CTX_DESTROY = 0x0201,
    VIRTGPU_CMD_CTX_ATTACH_RESOURCE = 0x0202,
    VIRTGPU_CMD_CTX_DETACH_RESOURCE = 0x0203,
    VIRTGPU_CMD_RESOURCE_CREATE_3D = 0x0204,
    VIRTGPU_CMD_TRANSFER_TO_HOST_3D = 0x0205,
    VIRTGPU_CMD_TRANSFER_FROM_HOST_3D = 0x0206,
    VIRTGPU_CMD_SUBMIT_3D = 0x0207,
    VIRTGPU_CMD_RESOURCE_MAP_BLOB = 0x0208,
    VIRTGPU_CMD_RESOURCE_UNMAP_BLOB = 0x0209,
    VIRTGPU_CMD_UPDATE_CURSOR = 0x0300,
    VIRTGPU_CMD_MOVE_CURSOR = 0x0301,
    VIRTGPU_RESP_OK_NODATA = 0x1100,
    VIRTGPU_RESP_OK_DISPLAY_INFO = 0x1101,
    VIRTGPU_RESP_OK_CAPSET_INFO = 0x1102,
    VIRTGPU_RESP_OK_CAPSET = 0x1103,
    VIRTGPU_RESP_OK_EDID = 0x1104,
    VIRTGPU_RESP_OK_RESOURCE_UUID = 0x1105,
    VIRTGPU_RESP_OK_MAP_INFO = 0x1106,
    VIRTGPU_RESP_ERR_UNSPEC = 0x1200,
    VIRTGPU_RESP_ERR_OUT_OF_MEMORY = 0x1201,
    VIRTGPU_RESP_ERR_INVALID_SCANOUT_ID = 0x1202,
    VIRTGPU_RESP_ERR_INVALID_RESOURCE_ID = 0x1203,
    VIRTGPU_RESP_ERR_INVALID_CONTEXT_ID = 0x1204,
    VIRTGPU_RESP_ERR_INVALID_PARAMETER = 0x1205
} VIRTGPU_CTRL_TYPE;

typedef enum _VIRTGPU_FORMAT
{
    VIRTGPU_FORMAT_B8G8R8A8_UNORM = 1,
    VIRTGPU_FORMAT_B8G8R8X8_UNORM = 2,
    VIRTGPU_FORMAT_A8R8G8B8_UNORM = 3,
    VIRTGPU_FORMAT_X8R8G8B8_UNORM = 4,
    VIRTGPU_FORMAT_R8G8B8A8_UNORM = 67,
    VIRTGPU_FORMAT_X8B8G8R8_UNORM = 68,
    VIRTGPU_FORMAT_A8B8G8R8_UNORM = 121,
    VIRTGPU_FORMAT_R8G8B8X8_UNORM = 134
} VIRTGPU_FORMAT;

#include <pshpack1.h>
typedef struct _VIRTGPU_CTRL_HDR
{
    ULONG Type;
    ULONG Flags;
    ULONGLONG FenceId;
    ULONG ContextId;
    UCHAR RingIndex;
    UCHAR Padding[3];
} VIRTGPU_CTRL_HDR, *PVIRTGPU_CTRL_HDR;

typedef struct _VIRTGPU_RECT
{
    ULONG X;
    ULONG Y;
    ULONG Width;
    ULONG Height;
} VIRTGPU_RECT, *PVIRTGPU_RECT;

typedef struct _VIRTGPU_DISPLAY_ONE
{
    VIRTGPU_RECT Rect;
    ULONG Enabled;
    ULONG Flags;
} VIRTGPU_DISPLAY_ONE, *PVIRTGPU_DISPLAY_ONE;

typedef struct _VIRTGPU_RESP_DISPLAY_INFO
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_DISPLAY_ONE Modes[16];
} VIRTGPU_RESP_DISPLAY_INFO, *PVIRTGPU_RESP_DISPLAY_INFO;

typedef struct _VIRTGPU_CONFIG
{
    ULONG EventsRead;
    ULONG EventsClear;
    ULONG NumScanouts;
    ULONG NumCapsets;
} VIRTGPU_CONFIG, *PVIRTGPU_CONFIG;

typedef struct _VIRTGPU_RESOURCE_CREATE_2D
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Format;
    ULONG Width;
    ULONG Height;
} VIRTGPU_RESOURCE_CREATE_2D, *PVIRTGPU_RESOURCE_CREATE_2D;

typedef struct _VIRTGPU_RESOURCE_UNREF
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_RESOURCE_UNREF, *PVIRTGPU_RESOURCE_UNREF;

typedef struct _VIRTGPU_RESOURCE_ATTACH_BACKING
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG EntryCount;
} VIRTGPU_RESOURCE_ATTACH_BACKING, *PVIRTGPU_RESOURCE_ATTACH_BACKING;

typedef struct _VIRTGPU_MEM_ENTRY
{
    ULONGLONG Address;
    ULONG Length;
    ULONG Padding;
} VIRTGPU_MEM_ENTRY, *PVIRTGPU_MEM_ENTRY;

typedef struct _VIRTGPU_RESOURCE_DETACH_BACKING
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_RESOURCE_DETACH_BACKING, *PVIRTGPU_RESOURCE_DETACH_BACKING;

typedef struct _VIRTGPU_SET_SCANOUT
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_RECT Rect;
    ULONG ScanoutId;
    ULONG ResourceId;
} VIRTGPU_SET_SCANOUT, *PVIRTGPU_SET_SCANOUT;

typedef struct _VIRTGPU_TRANSFER_TO_HOST_2D
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_RECT Rect;
    ULONGLONG Offset;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_TRANSFER_TO_HOST_2D, *PVIRTGPU_TRANSFER_TO_HOST_2D;

typedef struct _VIRTGPU_RESOURCE_FLUSH
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_RECT Rect;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_RESOURCE_FLUSH, *PVIRTGPU_RESOURCE_FLUSH;

typedef struct _VIRTGPU_BOX
{
    ULONG X;
    ULONG Y;
    ULONG Z;
    ULONG Width;
    ULONG Height;
    ULONG Depth;
} VIRTGPU_BOX, *PVIRTGPU_BOX;

typedef struct _VIRTGPU_TRANSFER_HOST_3D
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_BOX Box;
    ULONGLONG Offset;
    ULONG ResourceId;
    ULONG Level;
    ULONG Stride;
    ULONG LayerStride;
} VIRTGPU_TRANSFER_HOST_3D, *PVIRTGPU_TRANSFER_HOST_3D;

typedef struct _VIRTGPU_RESOURCE_CREATE_3D
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Target;
    ULONG Format;
    ULONG Bind;
    ULONG Width;
    ULONG Height;
    ULONG Depth;
    ULONG ArraySize;
    ULONG LastLevel;
    ULONG NrSamples;
    ULONG Flags;
    ULONG Padding;
} VIRTGPU_RESOURCE_CREATE_3D, *PVIRTGPU_RESOURCE_CREATE_3D;

typedef struct _VIRTGPU_CTX_CREATE
{
    VIRTGPU_CTRL_HDR Header;
    ULONG NameLength;
    ULONG ContextInit;
    CHAR DebugName[VIRTGPU_SHARED_CONTEXT_NAME_SIZE];
} VIRTGPU_CTX_CREATE, *PVIRTGPU_CTX_CREATE;

typedef struct _VIRTGPU_CTX_DESTROY
{
    VIRTGPU_CTRL_HDR Header;
} VIRTGPU_CTX_DESTROY, *PVIRTGPU_CTX_DESTROY;

typedef struct _VIRTGPU_CTX_RESOURCE
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_CTX_RESOURCE, *PVIRTGPU_CTX_RESOURCE;

typedef struct _VIRTGPU_SUBMIT_3D
{
    VIRTGPU_CTRL_HDR Header;
    ULONG Size;
    ULONG Padding;
} VIRTGPU_SUBMIT_3D, *PVIRTGPU_SUBMIT_3D;

typedef struct _VIRTGPU_GET_CAPSET_INFO
{
    VIRTGPU_CTRL_HDR Header;
    ULONG CapsetIndex;
    ULONG Padding;
} VIRTGPU_GET_CAPSET_INFO, *PVIRTGPU_GET_CAPSET_INFO;

typedef struct _VIRTGPU_RESP_CAPSET_INFO
{
    VIRTGPU_CTRL_HDR Header;
    ULONG CapsetId;
    ULONG CapsetMaxVersion;
    ULONG CapsetMaxSize;
    ULONG Padding;
} VIRTGPU_RESP_CAPSET_INFO, *PVIRTGPU_RESP_CAPSET_INFO;

typedef struct _VIRTGPU_GET_CAPSET
{
    VIRTGPU_CTRL_HDR Header;
    ULONG CapsetId;
    ULONG CapsetVersion;
} VIRTGPU_GET_CAPSET, *PVIRTGPU_GET_CAPSET;

typedef struct _VIRTGPU_RESP_CAPSET
{
    VIRTGPU_CTRL_HDR Header;
    UCHAR CapsetData[1];
} VIRTGPU_RESP_CAPSET, *PVIRTGPU_RESP_CAPSET;

typedef struct _VIRTGPU_GET_EDID
{
    VIRTGPU_CTRL_HDR Header;
    ULONG Scanout;
    ULONG Padding;
} VIRTGPU_GET_EDID, *PVIRTGPU_GET_EDID;

typedef struct _VIRTGPU_RESP_EDID
{
    VIRTGPU_CTRL_HDR Header;
    ULONG Size;
    ULONG Padding;
    UCHAR Edid[VIRTGPU_EDID_SIZE];
} VIRTGPU_RESP_EDID, *PVIRTGPU_RESP_EDID;

typedef struct _VIRTGPU_RESOURCE_ASSIGN_UUID
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_RESOURCE_ASSIGN_UUID, *PVIRTGPU_RESOURCE_ASSIGN_UUID;

typedef struct _VIRTGPU_RESP_RESOURCE_UUID
{
    VIRTGPU_CTRL_HDR Header;
    UCHAR Uuid[16];
} VIRTGPU_RESP_RESOURCE_UUID, *PVIRTGPU_RESP_RESOURCE_UUID;

typedef struct _VIRTGPU_RESOURCE_CREATE_BLOB
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG BlobMem;
    ULONG BlobFlags;
    ULONG EntryCount;
    ULONGLONG BlobId;
    ULONGLONG Size;
} VIRTGPU_RESOURCE_CREATE_BLOB, *PVIRTGPU_RESOURCE_CREATE_BLOB;

typedef struct _VIRTGPU_RESOURCE_MAP_BLOB
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
    ULONGLONG Offset;
} VIRTGPU_RESOURCE_MAP_BLOB, *PVIRTGPU_RESOURCE_MAP_BLOB;

typedef struct _VIRTGPU_RESP_MAP_INFO
{
    VIRTGPU_CTRL_HDR Header;
    ULONG MapInfo;
    ULONG Padding;
} VIRTGPU_RESP_MAP_INFO, *PVIRTGPU_RESP_MAP_INFO;

typedef struct _VIRTGPU_RESOURCE_UNMAP_BLOB
{
    VIRTGPU_CTRL_HDR Header;
    ULONG ResourceId;
    ULONG Padding;
} VIRTGPU_RESOURCE_UNMAP_BLOB, *PVIRTGPU_RESOURCE_UNMAP_BLOB;

typedef struct _VIRTGPU_CURSOR_POS
{
    ULONG ScanoutId;
    ULONG X;
    ULONG Y;
    ULONG Padding;
} VIRTGPU_CURSOR_POS, *PVIRTGPU_CURSOR_POS;

typedef struct _VIRTGPU_UPDATE_CURSOR
{
    VIRTGPU_CTRL_HDR Header;
    VIRTGPU_CURSOR_POS Pos;
    ULONG ResourceId;
    ULONG HotX;
    ULONG HotY;
    ULONG Padding;
} VIRTGPU_UPDATE_CURSOR, *PVIRTGPU_UPDATE_CURSOR;
#include <poppack.h>

C_ASSERT(sizeof(VIRTGPU_CTRL_HDR) == 24);
C_ASSERT(sizeof(VIRTGPU_MEM_ENTRY) == 16);

typedef struct _VIRTGPU_BAR
{
    PHYSICAL_ADDRESS Base;
    ULONG Length;
    BOOLEAN InIoSpace;
} VIRTGPU_BAR, *PVIRTGPU_BAR;

typedef struct _VIRTGPU_SHARED_ALLOCATION
{
    PVOID VirtualAddress;
    ULONG Length;
    PHYSICAL_ADDRESS PhysicalAddress;
} VIRTGPU_SHARED_ALLOCATION, *PVIRTGPU_SHARED_ALLOCATION;

typedef struct _VIRTGPU_3D_CONTEXT_STATE
{
    BOOLEAN InUse;
    ULONG ContextId;
} VIRTGPU_3D_CONTEXT_STATE, *PVIRTGPU_3D_CONTEXT_STATE;

typedef struct _VIRTGPU_3D_RESOURCE_STATE
{
    BOOLEAN InUse;
    BOOLEAN BackingAttached;
    BOOLEAN Blob;
    BOOLEAN BlobMapped;
    BOOLEAN UuidValid;
    ULONG ResourceId;
    ULONG BackingSize;
    ULONG BlobMem;
    ULONG BlobFlags;
    ULONG BlobMapInfo;
    PVOID BackingVirtual;
    PHYSICAL_ADDRESS BackingPhysical;
    ULONGLONG BlobSize;
    ULONGLONG BlobId;
    UCHAR Uuid[16];
} VIRTGPU_3D_RESOURCE_STATE, *PVIRTGPU_3D_RESOURCE_STATE;

typedef struct _VIRTGPU_DEVICE_EXTENSION
{
    ULONG PciBusNumber;
    ULONG PciSlot;
    PCI_COMMON_HEADER PciHeader;
    VIRTGPU_BAR Bars[PCI_TYPE0_ADDRESSES];

    VirtIODevice VirtIODevice;
    struct virtqueue* ControlQueue;
    struct virtqueue* CursorQueue;
    VIRTGPU_SHARED_ALLOCATION SharedAllocations[VIRTGPU_MAX_SHARED_ALLOCATIONS];
    VIRTGPU_3D_CONTEXT_STATE Contexts[VIRTGPU_MAX_3D_CONTEXTS];
    VIRTGPU_3D_RESOURCE_STATE Resources[VIRTGPU_MAX_3D_RESOURCES];

    PVOID CommandBuffer;
    PHYSICAL_ADDRESS CommandPhysical;
    PVOID AsyncCommandBuffer;
    PHYSICAL_ADDRESS AsyncCommandPhysical;
    PVOID CursorCommandBuffer;
    PHYSICAL_ADDRESS CursorCommandPhysical;
    PVOID FrameBufferVirtual;
    PHYSICAL_ADDRESS FrameBufferPhysical;
    ULONG FrameBufferSize;
    PVOID CursorBufferVirtual;
    PHYSICAL_ADDRESS CursorBufferPhysical;
    ULONG CursorBufferSize;
    ULONG CursorWidth;
    ULONG CursorHeight;
    ULONG CursorX;
    ULONG CursorY;
    ULONG CursorCommandNextSlot;
    ULONG MaxScreenWidth;
    ULONG MaxScreenHeight;
    ULONG ScreenWidth;
    ULONG ScreenHeight;
    ULONG BytesPerPixel;
    ULONG PixelsPerScanLine;
    ULONG BytesPerScanLine;
    ULONG CurrentMode;
    ULONG ModeCount;
    ULONGLONG HostFeatures;
    ULONGLONG GuestFeatures;
    ULONG NumScanouts;
    ULONG NumCapsets;
    ULONG CapsetCount;
    ULONG NextContextId;
    ULONG NextResourceId;
    ULONG SupportedCapsetMask;
    ULONG PreferredCapsetId;
    ULONG PreferredCapsetVersion;
    ULONGLONG NextFenceId;
    ULONGLONG CompletedFenceId;
    VIRTGPU_3D_CAPSET_INFO Capsets[VIRTGPU_MAX_CAPSETS];
    UCHAR Edid[VIRTGPU_SHARED_EDID_SIZE];
    ULONG EdidSize;
    BOOLEAN HardwareReady;
    BOOLEAN VirglSupported;
    BOOLEAN EdidSupported;
    BOOLEAN ResourceUuidSupported;
    BOOLEAN ResourceBlobSupported;
    BOOLEAN EdidValid;
    BOOLEAN ContextInitSupported;
    BOOLEAN FlushPending;
    BOOLEAN CommandBusy;
    BOOLEAN CursorReady;
    BOOLEAN CursorShapeValid;
    BOOLEAN CursorEnabled;
    BOOLEAN CursorCommandInUse[VIRTGPU_CURSOR_COMMAND_COUNT];
    BOOLEAN AsyncCommandInUse[VIRTGPU_ASYNC_COMMAND_COUNT];
    PVOID MappedFrameBuffer;
    VIDEO_MODE_INFORMATION ModeInfo[VIRTGPU_MAX_VIDEO_MODES];
} VIRTGPU_DEVICE_EXTENSION, *PVIRTGPU_DEVICE_EXTENSION;

ULONG
NTAPI
DriverEntry(
    _In_ PVOID Context1,
    _In_ PVOID Context2);

VP_STATUS
NTAPI
VirtGpuFindAdapter(
    _In_ PVOID HwDeviceExtension,
    _In_ PVOID HwContext,
    _In_ PWSTR ArgumentString,
    _Inout_ PVIDEO_PORT_CONFIG_INFO ConfigInfo,
    _Out_ PUCHAR Again);

BOOLEAN
NTAPI
VirtGpuInitialize(
    _In_ PVOID HwDeviceExtension);

BOOLEAN
NTAPI
VirtGpuStartIO(
    _In_ PVOID HwDeviceExtension,
    _In_ PVIDEO_REQUEST_PACKET RequestPacket);

BOOLEAN
NTAPI
VirtGpuResetHw(
    _In_ PVOID DeviceExtension,
    _In_ ULONG Columns,
    _In_ ULONG Rows);

VOID
NTAPI
VirtGpuTimer(
    _In_ PVOID HwDeviceExtension);

VP_STATUS
NTAPI
VirtGpuGetPowerState(
    _In_ PVOID HwDeviceExtension,
    _In_ ULONG HwId,
    _In_ PVIDEO_POWER_MANAGEMENT VideoPowerControl);

VP_STATUS
NTAPI
VirtGpuSetPowerState(
    _In_ PVOID HwDeviceExtension,
    _In_ ULONG HwId,
    _In_ PVIDEO_POWER_MANAGEMENT VideoPowerControl);

VP_STATUS
NTAPI
VirtGpuGetVideoChildDescriptor(
    _In_ PVOID HwDeviceExtension,
    _In_ PVIDEO_CHILD_ENUM_INFO ChildEnumInfo,
    _Out_ PVIDEO_CHILD_TYPE VideoChildType,
    _Out_ PUCHAR ChildDescriptor,
    _Out_ PULONG UId,
    _Out_ PULONG Unused);

#endif /* _VIRTGPU_PCH_ */
