/*
 * Shared private interface between the VirtIO GPU XPDM display driver and
 * miniport.
 */

#pragma once

#define IOCTL_VIDEO_VIRTGPU_FLUSH_RECT \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_QUERY_3D_CAPS \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_GET_CAPSET \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_CREATE_CONTEXT \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_DESTROY_CONTEXT \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_CREATE_RESOURCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_DESTROY_RESOURCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_TRANSFER_TO_HOST \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_TRANSFER_FROM_HOST \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_SUBMIT \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_ATTACH_RESOURCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_DETACH_RESOURCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_WAIT_FENCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_QUERY_EDID \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_CREATE_BLOB \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_ASSIGN_UUID \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_MAP_BLOB \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_UNMAP_BLOB \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_SET_SCANOUT_RESOURCE \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_RESOURCE_FLUSH_RECT \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_VIDEO_VIRTGPU_3D_EXECUTE_BATCH \
    CTL_CODE(FILE_DEVICE_VIDEO, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define VIRTGPU_ESCAPE_3D_IOCTL_CODE 0x56473344 /* "VG3D" */

#define VIRTGPU_3D_BATCH_VERSION 1
#define VIRTGPU_3D_MAX_BATCH_BYTES (64 * 1024)
#define VIRTGPU_3D_MAX_BATCH_COMMANDS 4096

#define VIRTGPU_3D_BATCH_OP_NOP 0
#define VIRTGPU_3D_BATCH_OP_SUBMIT 1
#define VIRTGPU_3D_BATCH_OP_TRANSFER_TO_HOST 2
#define VIRTGPU_3D_BATCH_OP_TRANSFER_FROM_HOST 3

#define VIRTGPU_SHARED_CAPSET_VIRGL 1
#define VIRTGPU_SHARED_CAPSET_VIRGL2 2
#define VIRTGPU_SHARED_CAPSET_GFXSTREAM_VULKAN 3
#define VIRTGPU_SHARED_CAPSET_VENUS 4
#define VIRTGPU_SHARED_CAPSET_CROSS_DOMAIN 5
#define VIRTGPU_SHARED_CAPSET_DRM 6

#define VIRTGPU_SHARED_BLOB_MEM_GUEST 0x0001
#define VIRTGPU_SHARED_BLOB_MEM_HOST3D 0x0002
#define VIRTGPU_SHARED_BLOB_MEM_HOST3D_GUEST 0x0003

#define VIRTGPU_SHARED_BLOB_FLAG_USE_MAPPABLE 0x0001
#define VIRTGPU_SHARED_BLOB_FLAG_USE_SHAREABLE 0x0002
#define VIRTGPU_SHARED_BLOB_FLAG_USE_CROSS_DEVICE 0x0004

#define VIRTGPU_SHARED_MAX_CAPSETS 8
#define VIRTGPU_SHARED_CONTEXT_NAME_SIZE 64
#define VIRTGPU_SHARED_EDID_SIZE 256

typedef struct _VIRTGPU_DIRTY_RECT
{
    LONG Left;
    LONG Top;
    LONG Right;
    LONG Bottom;
} VIRTGPU_DIRTY_RECT, *PVIRTGPU_DIRTY_RECT;

typedef struct _VIRTGPU_SCANOUT_RESOURCE
{
    ULONG ResourceId;
    ULONG X;
    ULONG Y;
    ULONG Width;
    ULONG Height;
} VIRTGPU_SCANOUT_RESOURCE, *PVIRTGPU_SCANOUT_RESOURCE;

typedef struct _VIRTGPU_RESOURCE_DIRTY_RECT
{
    ULONG ResourceId;
    LONG Left;
    LONG Top;
    LONG Right;
    LONG Bottom;
} VIRTGPU_RESOURCE_DIRTY_RECT, *PVIRTGPU_RESOURCE_DIRTY_RECT;

typedef struct _VIRTGPU_3D_CAPSET_INFO
{
    ULONG CapsetId;
    ULONG MaxVersion;
    ULONG MaxSize;
} VIRTGPU_3D_CAPSET_INFO, *PVIRTGPU_3D_CAPSET_INFO;

typedef struct _VIRTGPU_3D_CAPS
{
    ULONG Size;
    ULONG Enabled;
    ULONG ContextInitSupported;
    ULONG ResourceUuidSupported;
    ULONG ResourceBlobSupported;
    ULONG NumCapsets;
    ULONG SupportedCapsetMask;
    ULONG PreferredCapsetId;
    ULONG PreferredCapsetVersion;
    ULONG MaxCommandBytes;
    ULONG BatchSupported;
    ULONG MaxBatchBytes;
    ULONG MaxBatchCommands;
    ULONGLONG LastCompletedFenceId;
    ULONGLONG HostFeatures;
    ULONGLONG GuestFeatures;
    VIRTGPU_3D_CAPSET_INFO Capsets[VIRTGPU_SHARED_MAX_CAPSETS];
} VIRTGPU_3D_CAPS, *PVIRTGPU_3D_CAPS;

typedef struct _VIRTGPU_3D_GET_CAPSET
{
    ULONG CapsetId;
    ULONG CapsetVersion;
    ULONG Size;
    UCHAR Data[1];
} VIRTGPU_3D_GET_CAPSET, *PVIRTGPU_3D_GET_CAPSET;

typedef struct _VIRTGPU_3D_CREATE_CONTEXT
{
    ULONG ContextId;
    ULONG CapsetId;
    ULONG ContextInit;
    CHAR DebugName[VIRTGPU_SHARED_CONTEXT_NAME_SIZE];
} VIRTGPU_3D_CREATE_CONTEXT, *PVIRTGPU_3D_CREATE_CONTEXT;

typedef struct _VIRTGPU_3D_CONTEXT
{
    ULONG ContextId;
} VIRTGPU_3D_CONTEXT, *PVIRTGPU_3D_CONTEXT;

typedef struct _VIRTGPU_3D_CREATE_RESOURCE
{
    ULONG ResourceId;
    ULONG Target;
    ULONG Format;
    ULONG Bind;
    ULONG Width;
    ULONG Height;
    ULONG Depth;
    ULONG ArraySize;
    ULONG LastLevel;
    ULONG NrSamples;
    ULONG Flags;
    ULONG BackingSize;
} VIRTGPU_3D_CREATE_RESOURCE, *PVIRTGPU_3D_CREATE_RESOURCE;

typedef struct _VIRTGPU_3D_CREATE_BLOB
{
    ULONG ResourceId;
    ULONG ContextId;
    ULONG BlobMem;
    ULONG BlobFlags;
    ULONGLONG BlobId;
    ULONGLONG Size;
    ULONG BackingSize;
    ULONG MapInfo;
    ULONG CommandSize;
    UCHAR Commands[1];
} VIRTGPU_3D_CREATE_BLOB, *PVIRTGPU_3D_CREATE_BLOB;

typedef struct _VIRTGPU_3D_RESOURCE
{
    ULONG ResourceId;
} VIRTGPU_3D_RESOURCE, *PVIRTGPU_3D_RESOURCE;

typedef struct _VIRTGPU_3D_RESOURCE_UUID
{
    ULONG ResourceId;
    UCHAR Uuid[16];
} VIRTGPU_3D_RESOURCE_UUID, *PVIRTGPU_3D_RESOURCE_UUID;

typedef struct _VIRTGPU_3D_MAP_BLOB
{
    ULONG ResourceId;
    ULONG MapInfo;
    ULONGLONG Offset;
} VIRTGPU_3D_MAP_BLOB, *PVIRTGPU_3D_MAP_BLOB;

typedef struct _VIRTGPU_3D_CONTEXT_RESOURCE
{
    ULONG ContextId;
    ULONG ResourceId;
} VIRTGPU_3D_CONTEXT_RESOURCE, *PVIRTGPU_3D_CONTEXT_RESOURCE;

typedef struct _VIRTGPU_3D_TRANSFER
{
    ULONG ContextId;
    ULONG ResourceId;
    ULONG X;
    ULONG Y;
    ULONG Z;
    ULONG Width;
    ULONG Height;
    ULONG Depth;
    ULONG Level;
    ULONG Stride;
    ULONG LayerStride;
    ULONGLONG Offset;
    ULONGLONG FenceId;
    ULONG RingIndex;
    ULONG Size;
    UCHAR Data[1];
} VIRTGPU_3D_TRANSFER, *PVIRTGPU_3D_TRANSFER;

typedef struct _VIRTGPU_3D_SUBMIT
{
    ULONG ContextId;
    ULONGLONG FenceId;
    ULONG RingIndex;
    ULONG Size;
    UCHAR Commands[1];
} VIRTGPU_3D_SUBMIT, *PVIRTGPU_3D_SUBMIT;

typedef struct _VIRTGPU_3D_BATCH_COMMAND
{
    ULONG OpCode;
    ULONG Size;
} VIRTGPU_3D_BATCH_COMMAND, *PVIRTGPU_3D_BATCH_COMMAND;

typedef struct _VIRTGPU_3D_BATCH_TRANSFER
{
    ULONG ResourceId;
    ULONG X;
    ULONG Y;
    ULONG Z;
    ULONG Width;
    ULONG Height;
    ULONG Depth;
    ULONG Level;
    ULONG Stride;
    ULONG LayerStride;
    ULONGLONG Offset;
    ULONG Size;
    UCHAR Data[1];
} VIRTGPU_3D_BATCH_TRANSFER, *PVIRTGPU_3D_BATCH_TRANSFER;

typedef struct _VIRTGPU_3D_BATCH
{
    ULONG Version;
    ULONG ContextId;
    ULONGLONG FenceId;
    ULONG RingIndex;
    ULONG CommandCount;
    ULONG Size;
    UCHAR Commands[1];
} VIRTGPU_3D_BATCH, *PVIRTGPU_3D_BATCH;

typedef struct _VIRTGPU_3D_FENCE
{
    ULONGLONG FenceId;
    ULONG Completed;
    ULONG Reserved;
} VIRTGPU_3D_FENCE, *PVIRTGPU_3D_FENCE;

typedef struct _VIRTGPU_EDID
{
    ULONG Size;
    ULONG Valid;
    UCHAR Data[VIRTGPU_SHARED_EDID_SIZE];
} VIRTGPU_EDID, *PVIRTGPU_EDID;

typedef struct _VIRTGPU_ESCAPE_3D_IOCTL
{
    ULONG Size;
    ULONG IoControlCode;
    ULONG InputSize;
    UCHAR Data[1];
} VIRTGPU_ESCAPE_3D_IOCTL, *PVIRTGPU_ESCAPE_3D_IOCTL;
