@ stdcall DrvCopyContext(ptr ptr long)
@ stdcall DrvCreateContext(ptr)
@ stdcall DrvCreateLayerContext(ptr long)
@ stdcall DrvDeleteContext(ptr)
@ stdcall DrvDescribeLayerPlane(ptr long long long ptr)
@ stdcall DrvDescribePixelFormat(ptr long long ptr)
@ stdcall DrvGetLayerPaletteEntries(ptr long long long ptr)
@ stdcall DrvGetProcAddress(str)
@ stdcall DrvReleaseContext(ptr)
@ stdcall DrvRealizeLayerPalette(ptr long long)
@ stdcall DrvSetCallbackProcs(long ptr)
@ stdcall DrvSetContext(ptr ptr ptr)
@ stdcall DrvSetLayerPaletteEntries(ptr long long long ptr)
@ stdcall DrvSetPixelFormat(ptr long)
@ stdcall DrvShareLists(ptr ptr)
@ stdcall DrvSwapBuffers(ptr)
@ stdcall DrvSwapLayerBuffers(ptr long)
@ stdcall DrvValidateVersion(long)
@ stdcall VirtGpu3DIoControl(ptr long ptr long ptr long)
@ stdcall VirtGpu3DCurrentIoControl(long ptr long ptr long)
@ stdcall VirtGpu3DQueryCaps(ptr ptr)
@ stdcall VirtGpu3DGetCapset(ptr ptr long)
@ stdcall VirtGpu3DCreateContext(ptr ptr)
@ stdcall VirtGpu3DCreateVirglContext(ptr ptr ptr)
@ stdcall VirtGpu3DDestroyContext(ptr ptr)
@ stdcall VirtGpu3DCreateResource(ptr ptr)
@ stdcall VirtGpu3DDestroyResource(ptr ptr)
@ stdcall VirtGpu3DCreateBlob(ptr ptr long)
@ stdcall VirtGpu3DAssignUuid(ptr ptr)
@ stdcall VirtGpu3DMapBlob(ptr ptr)
@ stdcall VirtGpu3DUnmapBlob(ptr ptr)
@ stdcall VirtGpu3DAttachResource(ptr ptr)
@ stdcall VirtGpu3DDetachResource(ptr ptr)
@ stdcall VirtGpu3DTransferToHost(ptr ptr long)
@ stdcall VirtGpu3DTransferFromHost(ptr ptr long)
@ stdcall VirtGpu3DSubmit(ptr ptr long)
@ stdcall VirtGpu3DExecuteBatch(ptr ptr long)
@ stdcall VirtGpu3DWaitFence(ptr ptr)
