/*
 * PROJECT:     ReactOS Disk Management
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Resources header.
 */

#pragma once

/* Menu IDs */
#define IDI_DISKMGMT                1
#define IDB_TB_BACK                 10
#define IDB_TB_FORWARD              11
#define IDB_TB_RESCAN               12
#define IDB_TB_REFRESH              13
#define IDB_TB_CREATE               14
#define IDB_TB_DELETE               15
#define IDB_TB_PROPERTIES           16
#define IDB_TB_HELP                 17
#define IDB_LV_VOLUME               18
#define IDB_LV_PARTITION            19
#define IDM_DISKMGMT                32770
#define IDM_FILE_EXIT               32771
#define IDM_NAV_BACK                32772
#define IDM_NAV_FORWARD             32773
#define IDM_ACTION_EXTEND_VOLUME    32776
#define IDM_ACTION_SHRINK_VOLUME    32777
#define IDM_ACTION_RESCAN           32780
#define IDM_ACTION_REFRESH          32781
#define IDM_ACTION_INITIALIZE_DISK  32782
#define IDM_ACTION_CREATE_PARTITION 32783
#define IDM_ACTION_DELETE_VOLUME    32784
#define IDM_ACTION_PROPERTIES       32785
#define IDM_ACTION_ASSIGN_LETTER    32786
#define IDM_ACTION_REMOVE_LETTER    32787
#define IDM_ACTION_FORMAT           32794
#define IDM_ACTION_CHANGE_MOUNT_PATH 32795
#define IDM_ACTION_REMOVE_MOUNT_PATH 32796
#define IDM_ACTION_CONVERT_GPT      32797
#define IDM_ACTION_CONVERT_MBR      32798
#define IDM_ACTION_ONLINE           32788
#define IDM_ACTION_OFFLINE          32789
#define IDM_ACTION_SET_READ_ONLY    32790
#define IDM_ACTION_CLEAR_READ_ONLY  32791
#define IDM_ACTION_MARK_ACTIVE      32792
#define IDM_ACTION_MARK_INACTIVE    32793
#define IDM_VIEW_TOP                32800
#define IDM_VIEW_BOTTOM             32801
#define IDM_VIEW_DISK_LIST          32802
#define IDM_HELP_ABOUT              32810

/* Accelerator IDs */
#define IDA_DISKMGMT                33000

/* Dialog IDs */
#define IDD_ASSIGN_LETTER           34000
#define IDC_ASSIGN_LETTER_COMBO     34001
#define IDD_CREATE_PARTITION        34010
#define IDC_CREATE_PARTITION_PROMPT 34046
#define IDC_CREATE_PARTITION_SIZE   34011
#define IDC_CREATE_PARTITION_MAX    34012
#define IDC_CREATE_PARTITION_SIZE_LABEL 34047
#define IDC_CREATE_PARTITION_ASSIGN 34013
#define IDC_CREATE_PARTITION_LETTER 34014
#define IDC_CREATE_PARTITION_FORMAT 34015
#define IDC_CREATE_PARTITION_FS     34016
#define IDC_CREATE_PARTITION_LABEL  34017
#define IDC_CREATE_PARTITION_QUICK  34018
#define IDC_CREATE_PARTITION_TYPE   34019
#define IDD_FORMAT_VOLUME           34020
#define IDC_FORMAT_FILESYSTEM       34021
#define IDC_FORMAT_LABEL            34022
#define IDC_FORMAT_QUICK            34023
#define IDD_SELECT_MOUNT_PATH       34030
#define IDC_SELECT_MOUNT_PATH_PROMPT 34031
#define IDC_SELECT_MOUNT_PATH_LIST  34032
#define IDC_SELECT_MOUNT_PATH_REPLACE 34033
#define IDD_EXTEND_VOLUME           34040
#define IDD_SHRINK_VOLUME           34041
#define IDC_RESIZE_CURRENT          34042
#define IDC_RESIZE_LIMIT            34043
#define IDC_RESIZE_AMOUNT           34044

/* String IDs */
#define IDS_COPYRIGHT               100
#define IDS_APPNAME                 101
#define IDS_STATUS_READY            102
#define IDS_STATUS_RESCANNING       103
#define IDS_STATUS_REFRESHING       104
#define IDS_STATUS_INITIALIZING_DISK 105
#define IDS_STATUS_CREATING_PARTITION 106
#define IDS_STATUS_DELETING_VOLUME  107
#define IDS_STATUS_PROPERTIES       108
#define IDS_STATUS_ASSIGNING_LETTER 109
#define IDS_STATUS_REMOVING_LETTER  110
#define IDS_STATUS_ONLINING_DISK    111
#define IDS_STATUS_OFFLINING_DISK   112
#define IDS_STATUS_SETTING_READ_ONLY 113
#define IDS_STATUS_CLEARING_READ_ONLY 114
#define IDS_STATUS_MARKING_ACTIVE   115
#define IDS_STATUS_MARKING_INACTIVE 116
#define IDS_STATUS_FORMATTING_VOLUME 117
#define IDS_STATUS_CHANGING_MOUNT_PATH 118
#define IDS_STATUS_REMOVING_MOUNT_PATH 119
#define IDS_STATUS_CONVERTING_GPT   170
#define IDS_STATUS_CONVERTING_MBR   171
#define IDS_STATUS_EXTENDING_VOLUME 181
#define IDS_STATUS_SHRINKING_VOLUME 182
#define IDS_CREATE_PROMPT_VOLUME    183
#define IDS_CREATE_PROMPT_PARTITION 184
#define IDS_CREATE_PROMPT_LOGICAL   185
#define IDS_CREATE_SIZE_LABEL_VOLUME 186
#define IDS_CREATE_SIZE_LABEL_PARTITION 187
#define IDS_CREATE_SIZE_LABEL_LOGICAL 188

#define IDS_HINT_READY              120
#define IDS_HINT_FILE_EXIT          121
#define IDS_HINT_ACTION_RESCAN      122
#define IDS_HINT_ACTION_REFRESH     123
#define IDS_HINT_ACTION_INITIALIZE_DISK 124
#define IDS_HINT_ACTION_CREATE_PARTITION 125
#define IDS_HINT_ACTION_DELETE_VOLUME 126
#define IDS_HINT_ACTION_PROPERTIES  127
#define IDS_HINT_ACTION_ASSIGN_LETTER 128
#define IDS_HINT_ACTION_REMOVE_LETTER 129
#define IDS_HINT_VIEW_TOP           130
#define IDS_HINT_VIEW_BOTTOM        131
#define IDS_HINT_VIEW_DISK_LIST     132
#define IDS_HINT_HELP_ABOUT         133
#define IDS_HINT_ACTION_ONLINE      134
#define IDS_HINT_ACTION_OFFLINE     135
#define IDS_HINT_ACTION_SET_READ_ONLY 136
#define IDS_HINT_ACTION_CLEAR_READ_ONLY 137
#define IDS_HINT_ACTION_MARK_ACTIVE 138
#define IDS_HINT_ACTION_MARK_INACTIVE 139
#define IDS_HINT_ACTION_FORMAT      140
#define IDS_HINT_ACTION_CHANGE_MOUNT_PATH 141
#define IDS_HINT_ACTION_REMOVE_MOUNT_PATH 142
#define IDS_HINT_ACTION_CONVERT_GPT 172
#define IDS_HINT_ACTION_CONVERT_MBR 173
#define IDS_HINT_ACTION_EXTEND_VOLUME 183
#define IDS_HINT_ACTION_SHRINK_VOLUME 184

#define IDS_COL_VOLUME              150
#define IDS_COL_LAYOUT              151
#define IDS_COL_TYPE                152
#define IDS_COL_FILESYSTEM          153
#define IDS_COL_STATUS              154
#define IDS_COL_CAPACITY            155
#define IDS_COL_FREE                156
#define IDS_COL_FREE_PCT            157
#define IDS_TOOLBAR_BACK            158
#define IDS_TOOLBAR_FORWARD         159
#define IDS_TOOLBAR_RESCAN          160
#define IDS_TOOLBAR_REFRESH         161
#define IDS_TOOLBAR_CREATE          162
#define IDS_TOOLBAR_DELETE          163
#define IDS_TOOLBAR_PROPERTIES      164
#define IDS_TOOLBAR_HELP            165
#define IDS_PARTITION_TYPE_PRIMARY  174
#define IDS_PARTITION_TYPE_BASIC    175
#define IDS_PARTITION_TYPE_EFI      176
#define IDS_PARTITION_TYPE_MSR      177
#define IDS_PARTITION_TYPE_RECOVERY 178
#define IDS_PARTITION_TYPE_EXTENDED 179
#define IDS_PARTITION_TYPE_LOGICAL  180
