#pragma once

#define ARM64_EARLY_TRAP_REGISTER_COUNT 31

#define ARM64_EARLY_TRAP_OFFSET_X(n) ((n) * 8ULL)
#define ARM64_EARLY_TRAP_OFFSET_X0 ARM64_EARLY_TRAP_OFFSET_X(0)
#define ARM64_EARLY_TRAP_OFFSET_SP  ARM64_EARLY_TRAP_OFFSET_X(ARM64_EARLY_TRAP_REGISTER_COUNT)
#define ARM64_EARLY_TRAP_OFFSET_PC  (ARM64_EARLY_TRAP_OFFSET_SP + 8ULL)
#define ARM64_EARLY_TRAP_OFFSET_PSTATE (ARM64_EARLY_TRAP_OFFSET_PC + 8ULL)
#define ARM64_EARLY_TRAP_CONTEXT_SIZE (ARM64_EARLY_TRAP_OFFSET_PSTATE + 8ULL)
#define ARM64_EARLY_TRAP_CONTEXT_ALLOC_SIZE ((ARM64_EARLY_TRAP_CONTEXT_SIZE + 15ULL) & ~15ULL)

#define ARM64_KSEG0_BASE 0xFFFF800000000000ULL

#ifndef __ASSEMBLER__

#include <stddef.h>

typedef struct _ARM64_EARLY_TRAP_REGISTERS
{
    UINT64 X[ARM64_EARLY_TRAP_REGISTER_COUNT];
    UINT64 Sp;
    UINT64 Pc;
    UINT64 Pstate;
} ARM64_EARLY_TRAP_REGISTERS, *PARM64_EARLY_TRAP_REGISTERS;

typedef struct _ARM64_EARLY_TRAP_STATE
{
    UINT64 VectorId;
    UINT64 ExceptionSyndrome;
    UINT64 FaultAddress;
    UINT64 Elr;
    UINT64 Spsr;
    ARM64_EARLY_TRAP_REGISTERS Registers;
} ARM64_EARLY_TRAP_STATE, *PARM64_EARLY_TRAP_STATE;

C_ASSERT(offsetof(ARM64_EARLY_TRAP_REGISTERS, X[0]) == ARM64_EARLY_TRAP_OFFSET_X0);
C_ASSERT(offsetof(ARM64_EARLY_TRAP_REGISTERS, Sp) == ARM64_EARLY_TRAP_OFFSET_SP);
C_ASSERT(sizeof(ARM64_EARLY_TRAP_REGISTERS) == ARM64_EARLY_TRAP_CONTEXT_SIZE);

typedef VOID (*PARM64_EARLY_LOG_SINK)(_In_reads_bytes_(Length) const CHAR *Text,
                                      _In_ SIZE_T Length);

VOID
KiArm64DumpEarlyTrapState(
    _In_ const ARM64_EARLY_TRAP_STATE *State,
    _In_opt_ PARM64_EARLY_LOG_SINK Sink);

VOID
KiArm64DumpTrapStateToLog(
    _In_ const ARM64_EARLY_TRAP_STATE *State);

VOID
KiArm64DumpBugCheckState(
    _In_ ULONG BugCheckCode,
    _In_ ULONG_PTR BugCheckParameter1,
    _In_ ULONG_PTR BugCheckParameter2,
    _In_ ULONG_PTR BugCheckParameter3,
    _In_ ULONG_PTR BugCheckParameter4,
    _In_opt_ PKTRAP_FRAME TrapFrame,
    _In_opt_ const CONTEXT *Context);

#endif /* __ASSEMBLER__ */
