include_directories(${REACTOS_SOURCE_DIR}/ntoskrnl/include)
add_library(sonyhid MODULE sonyhid.c sonyhid.rc)
set_module_type(sonyhid kernelmodedriver)
add_importlibs(sonyhid ntoskrnl hal hidparse)
add_cd_file(TARGET sonyhid DESTINATION reactos/system32/drivers NO_CAB FOR all)
add_driver_inf(sonyhid sonyhid.inf)
