/*
 * Copyright (C) 2026 Ahmed ARIF <arif.ing@outlook.com>
 *
 * wimage.c - CLI driver for native-wimage (pure C)
 *
 * Implements capture, apply, info, dir, extract, verify commands
 * with output format matching wimlib-imagex.
 *
 */

#include "wim_types.h"
#include "wim_format.h"
#include "wim_read.h"
#include "wim_write.h"
#include "wim_io.h"

/* Generated by CMake's configure_file() from libwim/wimage_version.h.in.
 * Defines WIMAGE_VERSION_STRING ("X.Y") from project(... VERSION X.Y).
 * Hand builds without CMake can define WIMAGE_VERSION_STRING via -D. */
#if __has_include("wimage_version.h")
#  include "wimage_version.h"
#endif
#ifndef WIMAGE_VERSION_STRING
#  define WIMAGE_VERSION_STRING "unknown"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- Command enum ---- */

enum Command {
    CMD_NONE, CMD_CAPTURE, CMD_APPLY, CMD_APPEND, CMD_DELETE,
    CMD_INFO, CMD_DIR, CMD_EXTRACT, CMD_VERIFY
};

/* ---- Global state (replaces CWimage members) ---- */

static enum Command g_cmd = CMD_NONE;
static char g_wim_path[4096];
static char g_source_or_target[4096];
static char g_image_name[256];
static char g_image_desc[256];
static int  g_image_index;
static int  g_boot;
static int  g_check;
static int  g_show_header;
static int  g_show_xml;
static int  g_show_blobs;
static int  g_detailed;
static int  g_threads = 1;
static char g_compress[64];
static char g_path_filter[4096];
static char g_dest_dir[4096];

#define MAX_EXTRACT_PATHS 256
static char* g_extract_paths[MAX_EXTRACT_PATHS];
static int   g_extract_path_count;

/* ---- Helpers ---- */

static int starts_with(const char* s, const char* prefix)
{
    size_t len = strlen(prefix);
    return strncmp(s, prefix, len) == 0;
}

static int is_number(const char* s)
{
    if (!s || !*s) return 0;
    while (*s) {
        if (*s < '0' || *s > '9') return 0;
        s++;
    }
    return 1;
}

/* ---- Print helpers ---- */

static void print_dentry_tree(const WimDentry* d, const char* prefix, int detailed)
{
    const char* path = (!prefix || !*prefix) ? "/" : prefix;

    if (detailed) {
        printf("----------------------------------------------------------------------------\n");
        printf("Full Path           = \"%s\"\n", path);
        printf("Attributes          = 0x%08x\n", d->attributes);
        if (d->attributes & WIM_FILE_ATTRIBUTE_DIRECTORY)
            printf("    FILE_ATTRIBUTE_DIRECTORY is set\n");
        if (d->attributes & WIM_FILE_ATTRIBUTE_READONLY)
            printf("    FILE_ATTRIBUTE_READONLY is set\n");
        if (d->attributes & WIM_FILE_ATTRIBUTE_HIDDEN)
            printf("    FILE_ATTRIBUTE_HIDDEN is set\n");
        if (d->attributes & WIM_FILE_ATTRIBUTE_SYSTEM)
            printf("    FILE_ATTRIBUTE_SYSTEM is set\n");
        if (d->attributes & WIM_FILE_ATTRIBUTE_ARCHIVE)
            printf("    FILE_ATTRIBUTE_ARCHIVE is set\n");
        if (d->creation_time) {
            char* ts = filetime_to_string(d->creation_time);
            printf("Creation Time       = %s\n", ts);
            free(ts);
        }
        if (d->last_access_time) {
            char* ts = filetime_to_string(d->last_access_time);
            printf("Last Access Time    = %s\n", ts);
            free(ts);
        }
        if (d->last_write_time) {
            char* ts = filetime_to_string(d->last_write_time);
            printf("Last Write Time     = %s\n", ts);
            free(ts);
        }

        /* Print SHA-1 hash for files */
        if (!(d->attributes & WIM_FILE_ATTRIBUTE_DIRECTORY)) {
            int zero = 1;
            int i;
            printf("Hash                = ");
            for (i = 0; i < 20; i++) {
                if (d->sha1[i]) zero = 0;
            }
            if (zero) {
                printf("0000000000000000000000000000000000000000\n");
            } else {
                for (i = 0; i < 20; i++)
                    printf("%02x", d->sha1[i]);
                printf("\n");
            }
            printf("File Size           = %llu\n", (unsigned long long)d->file_size);
        }
        printf("\n");
    } else {
        printf("%s\n", path);
    }

    for (size_t i = 0; i < d->child_count; i++) {
        const WimDentry* child = &d->children[i];
        char child_path[8192];
        if (!prefix || !*prefix || strcmp(prefix, "/") == 0)
            snprintf(child_path, sizeof(child_path), "/%s", child->name_utf8);
        else
            snprintf(child_path, sizeof(child_path), "%s/%s", prefix, child->name_utf8);
        print_dentry_tree(child, child_path, detailed);
    }
}

static void print_wim_info(const WimCtx* ctx)
{
    const WimHeader* hdr = &ctx->header;

    /* Determine compression type */
    const char* compress_type = "None";
    if (hdr->flags & WIM_HDR_FLAG_COMPRESSION) {
        if (hdr->flags & WIM_HDR_FLAG_COMPRESS_XPRESS)
            compress_type = "XPRESS";
        else if (hdr->flags & WIM_HDR_FLAG_COMPRESS_LZX)
            compress_type = "LZX";
        else if (hdr->flags & WIM_HDR_FLAG_COMPRESS_LZMS)
            compress_type = "LZMS";
        else
            compress_type = "Unknown";
    }

    /* Format GUID */
    char guid_str[64];
    snprintf(guid_str, sizeof(guid_str),
             "0x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x",
             hdr->guid[0], hdr->guid[1], hdr->guid[2], hdr->guid[3],
             hdr->guid[4], hdr->guid[5], hdr->guid[6], hdr->guid[7],
             hdr->guid[8], hdr->guid[9], hdr->guid[10], hdr->guid[11],
             hdr->guid[12], hdr->guid[13], hdr->guid[14], hdr->guid[15]);

    printf("WIM Information:\n");
    printf("----------------\n");
    printf("Path:           %s\n", g_wim_path);
    printf("GUID:           %s\n", guid_str);
    printf("Version:        %u\n", hdr->version);
    printf("Image Count:    %u\n", hdr->image_count);
    printf("Compression:    %s\n", compress_type);
    printf("Chunk Size:     %u bytes\n", hdr->chunk_size);
    printf("Part Number:    %u/%u\n", hdr->part_number, hdr->total_parts);
    printf("Boot Index:     %u\n", hdr->boot_index);

    /* Integrity info */
    uint64_t integ_sz = reshdr_get_size(&hdr->integrity);
    printf("Integrity Info: %s\n", integ_sz ? "yes" : "no");
}

static void print_header_info(const WimHeader* hdr)
{
    printf("\nHeader Details:\n");
    printf("---------------\n");
    printf("Magic:          %.8s\n", (const char*)hdr->magic);
    printf("Header Size:    %u\n", hdr->header_size);
    printf("Version:        0x%08x\n", hdr->version);
    printf("Flags:          0x%08x\n", hdr->flags);
    printf("Chunk Size:     %u\n", hdr->chunk_size);
    printf("Part Number:    %u\n", hdr->part_number);
    printf("Total Parts:    %u\n", hdr->total_parts);
    printf("Image Count:    %u\n", hdr->image_count);
    printf("Boot Index:     %u\n", hdr->boot_index);

    printf("\nLookup Table Resource:\n");
    printf("  Size:          %llu\n", (unsigned long long)reshdr_get_size(&hdr->lookup_table));
    printf("  Flags:         0x%02x\n", reshdr_get_flags(&hdr->lookup_table));
    printf("  Offset:        %llu\n", (unsigned long long)hdr->lookup_table.offset);
    printf("  Original Size: %llu\n", (unsigned long long)hdr->lookup_table.original_size);

    printf("\nXML Data Resource:\n");
    printf("  Size:          %llu\n", (unsigned long long)reshdr_get_size(&hdr->xml_data));
    printf("  Flags:         0x%02x\n", reshdr_get_flags(&hdr->xml_data));
    printf("  Offset:        %llu\n", (unsigned long long)hdr->xml_data.offset);
    printf("  Original Size: %llu\n", (unsigned long long)hdr->xml_data.original_size);

    printf("\nBoot Metadata Resource:\n");
    printf("  Size:          %llu\n", (unsigned long long)reshdr_get_size(&hdr->boot_metadata));
    printf("  Flags:         0x%02x\n", reshdr_get_flags(&hdr->boot_metadata));
    printf("  Offset:        %llu\n", (unsigned long long)hdr->boot_metadata.offset);
    printf("  Original Size: %llu\n", (unsigned long long)hdr->boot_metadata.original_size);

    printf("\nIntegrity Table Resource:\n");
    printf("  Size:          %llu\n", (unsigned long long)reshdr_get_size(&hdr->integrity));
    printf("  Flags:         0x%02x\n", reshdr_get_flags(&hdr->integrity));
    printf("  Offset:        %llu\n", (unsigned long long)hdr->integrity.offset);
    printf("  Original Size: %llu\n", (unsigned long long)hdr->integrity.original_size);
}

static void print_blob_info(const WimBlob* blobs, size_t count)
{
    printf("\nBlob Table (%u entries):\n", (unsigned)count);
    printf("%-44s  %12s  %12s  %12s  %5s  %5s\n",
           "SHA-1", "Orig Size", "Comp Size", "Offset", "Refs", "Flags");
    for (size_t i = 0; i < count; i++) {
        const WimBlob* b = &blobs[i];
        char sha1_str[44];
        for (int j = 0; j < 20; j++)
            snprintf(sha1_str + j * 2, 3, "%02x", b->sha1.hash[j]);
        sha1_str[40] = '\0';
        printf("%s  %12llu  %12llu  %12llu  %5u  0x%02x\n",
               sha1_str,
               (unsigned long long)b->original_size,
               (unsigned long long)b->compressed_size,
               (unsigned long long)b->offset,
               b->ref_count, b->flags);
    }
}

/* ---- Usage / help ---- */

static void print_version(void)
{
    printf("native-wimage v%s\n", WIMAGE_VERSION_STRING);
}

static void print_usage(void)
{
    printf("native-wimage v%s\n", WIMAGE_VERSION_STRING);
    printf("Usage:\n");
    printf("    native-wimage capture SOURCE WIMFILE [NAME [DESC]] [--compress=TYPE] [--threads=N] [--boot] [--check]\n");
    printf("    native-wimage apply WIMFILE [IMAGE] TARGET [--check]\n");
    printf("    native-wimage append SOURCE WIMFILE [NAME [DESC]] [--compress=TYPE] [--threads=N] [--boot] [--check]\n");
    printf("    native-wimage delete WIMFILE IMAGE\n");
    printf("    native-wimage info WIMFILE [IMAGE] [--header] [--xml] [--blobs]\n");
    printf("    native-wimage dir WIMFILE [IMAGE] [--detailed]\n");
    printf("    native-wimage extract WIMFILE IMAGE [PATH...] [--dest-dir=DIR]\n");
    printf("    native-wimage verify WIMFILE\n");
    printf("\n");
    printf("Compression types: none, xpress (default: xpress)\n");
    printf("Threading: --threads=N only affects XPRESS capture/append (default: 1)\n");
    printf("IMAGE can be a 1-based index number or image name.\n");
}

static void print_command_help(const char* cmd)
{
    if (strcmp(cmd, "capture") == 0)
        printf("Usage: native-wimage capture SOURCE WIMFILE [NAME [DESC]] [--compress=TYPE] [--threads=N] [--boot] [--check]\n");
    else if (strcmp(cmd, "apply") == 0)
        printf("Usage: native-wimage apply WIMFILE [IMAGE] TARGET [--check]\n");
    else if (strcmp(cmd, "append") == 0)
        printf("Usage: native-wimage append SOURCE WIMFILE [NAME [DESC]] [--compress=TYPE] [--threads=N] [--boot] [--check]\n");
    else if (strcmp(cmd, "delete") == 0)
        printf("Usage: native-wimage delete WIMFILE IMAGE\n");
    else if (strcmp(cmd, "info") == 0)
        printf("Usage: native-wimage info WIMFILE [IMAGE] [--header] [--xml] [--blobs]\n");
    else if (strcmp(cmd, "dir") == 0)
        printf("Usage: native-wimage dir WIMFILE [IMAGE] [--detailed]\n");
    else if (strcmp(cmd, "extract") == 0)
        printf("Usage: native-wimage extract WIMFILE IMAGE [PATH...] [--dest-dir=DIR]\n");
    else if (strcmp(cmd, "verify") == 0)
        printf("Usage: native-wimage verify WIMFILE\n");
}

/* ---- Argument parsing ---- */

static int parse_args(int argc, char* argv[])
{
    if (argc < 2) {
        print_usage();
        return 0;
    }

    const char* cmd = argv[1];

    if (strcmp(cmd, "capture") == 0)       g_cmd = CMD_CAPTURE;
    else if (strcmp(cmd, "apply") == 0)    g_cmd = CMD_APPLY;
    else if (strcmp(cmd, "append") == 0)   g_cmd = CMD_APPEND;
    else if (strcmp(cmd, "delete") == 0)   g_cmd = CMD_DELETE;
    else if (strcmp(cmd, "info") == 0)     g_cmd = CMD_INFO;
    else if (strcmp(cmd, "dir") == 0)      g_cmd = CMD_DIR;
    else if (strcmp(cmd, "extract") == 0)  g_cmd = CMD_EXTRACT;
    else if (strcmp(cmd, "verify") == 0)   g_cmd = CMD_VERIFY;
    else if (strcmp(cmd, "--help") == 0 || strcmp(cmd, "-h") == 0 || strcmp(cmd, "help") == 0) {
        print_usage();
        return 0;
    } else if (strcmp(cmd, "--version") == 0 || strcmp(cmd, "-V") == 0 || strcmp(cmd, "version") == 0) {
        print_version();
        return 0;
    } else {
        fprintf(stderr, "Error: unknown command \"%s\"\n\n", cmd);
        print_usage();
        return 0;
    }

    /* Collect positional args and options */
    const char* positional[64];
    int pos_count = 0;

    for (int i = 2; i < argc; i++) {
        const char* arg = argv[i];
        if (starts_with(arg, "--compress=")) {
            snprintf(g_compress, sizeof(g_compress), "%s", arg + 11);
        } else if (starts_with(arg, "--threads=")) {
            g_threads = atoi(arg + 10);
            if (g_threads < 1) g_threads = 1;
        } else if (strcmp(arg, "--boot") == 0) {
            g_boot = 1;
        } else if (strcmp(arg, "--check") == 0) {
            g_check = 1;
        } else if (strcmp(arg, "--header") == 0) {
            g_show_header = 1;
        } else if (strcmp(arg, "--xml") == 0) {
            g_show_xml = 1;
        } else if (strcmp(arg, "--blobs") == 0) {
            g_show_blobs = 1;
        } else if (strcmp(arg, "--detailed") == 0) {
            g_detailed = 1;
        } else if (starts_with(arg, "--path=")) {
            snprintf(g_path_filter, sizeof(g_path_filter), "%s", arg + 7);
        } else if (starts_with(arg, "--dest-dir=")) {
            snprintf(g_dest_dir, sizeof(g_dest_dir), "%s", arg + 11);
        } else {
            if (pos_count < 64)
                positional[pos_count++] = arg;
        }
    }

    /* Parse positional args depending on command */
    int pi = 0;

    switch (g_cmd) {
    case CMD_CAPTURE:
    case CMD_APPEND:
        /* capture/append SOURCE WIMFILE [NAME [DESC]] */
        if (pos_count < 2) {
            fprintf(stderr, "Error: %s requires SOURCE and WIMFILE\n", cmd);
            print_command_help(cmd);
            return 0;
        }
        snprintf(g_source_or_target, sizeof(g_source_or_target), "%s", positional[0]);
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[1]);
        if (pos_count > 2) snprintf(g_image_name, sizeof(g_image_name), "%s", positional[2]);
        if (pos_count > 3) snprintf(g_image_desc, sizeof(g_image_desc), "%s", positional[3]);
        break;

    case CMD_APPLY:
        /* apply WIMFILE [IMAGE] TARGET */
        if (pos_count < 2) {
            fprintf(stderr, "Error: apply requires WIMFILE and TARGET\n");
            print_command_help("apply");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        pi = 1;
        if (pos_count >= 3 && is_number(positional[1])) {
            g_image_index = atoi(positional[1]);
            pi = 2;
        }
        if (pi >= pos_count) {
            fprintf(stderr, "Error: apply requires TARGET\n");
            print_command_help("apply");
            return 0;
        }
        snprintf(g_source_or_target, sizeof(g_source_or_target), "%s", positional[pi]);
        break;

    case CMD_DELETE:
        /* delete WIMFILE IMAGE */
        if (pos_count < 2) {
            fprintf(stderr, "Error: delete requires WIMFILE and IMAGE\n");
            print_command_help("delete");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        if (is_number(positional[1]))
            g_image_index = atoi(positional[1]);
        else
            snprintf(g_image_name, sizeof(g_image_name), "%s", positional[1]);
        break;

    case CMD_INFO:
        /* info WIMFILE [IMAGE] */
        if (pos_count < 1) {
            fprintf(stderr, "Error: info requires WIMFILE\n");
            print_command_help("info");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        if (pos_count > 1) {
            if (is_number(positional[1]))
                g_image_index = atoi(positional[1]);
            else
                snprintf(g_image_name, sizeof(g_image_name), "%s", positional[1]);
        }
        break;

    case CMD_DIR:
        /* dir WIMFILE [IMAGE] */
        if (pos_count < 1) {
            fprintf(stderr, "Error: dir requires WIMFILE\n");
            print_command_help("dir");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        if (pos_count > 1) {
            if (is_number(positional[1]))
                g_image_index = atoi(positional[1]);
            else
                snprintf(g_image_name, sizeof(g_image_name), "%s", positional[1]);
        }
        break;

    case CMD_EXTRACT:
        /* extract WIMFILE IMAGE [PATH...] */
        if (pos_count < 2) {
            fprintf(stderr, "Error: extract requires WIMFILE and IMAGE\n");
            print_command_help("extract");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        if (is_number(positional[1]))
            g_image_index = atoi(positional[1]);
        else
            snprintf(g_image_name, sizeof(g_image_name), "%s", positional[1]);
        for (int i = 2; i < pos_count && g_extract_path_count < MAX_EXTRACT_PATHS; i++) {
            g_extract_paths[g_extract_path_count] = strdup(positional[i]);
            g_extract_path_count++;
        }
        break;

    case CMD_VERIFY:
        /* verify WIMFILE */
        if (pos_count < 1) {
            fprintf(stderr, "Error: verify requires WIMFILE\n");
            print_command_help("verify");
            return 0;
        }
        snprintf(g_wim_path, sizeof(g_wim_path), "%s", positional[0]);
        break;

    default:
        break;
    }

    return 1;
}

/* ---- Commands ---- */

static int do_capture(void)
{
    int use_xpress = 1;
    if (strcmp(g_compress, "none") == 0)
        use_xpress = 0;
    else if (strcmp(g_compress, "xpress") == 0)
        use_xpress = 1;
    else {
        fprintf(stderr, "Error: unsupported compression \"%s\" (use \"none\" or \"xpress\")\n",
                g_compress);
        return 1;
    }

    const char* name = g_image_name[0] ? g_image_name : "Image";
    const char* desc = g_image_desc[0] ? g_image_desc : "";

    printf("Scanning \"%s\"\n", g_source_or_target);

    WimCtx ctx;
    wim_ctx_init(&ctx);
    ctx.num_threads = g_threads;

    int ret = wim_create(&ctx, g_wim_path, use_xpress);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to create WIM file \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    ret = wim_capture_tree(&ctx, g_source_or_target, name, desc);
    if (ret != 0) {
        fprintf(stderr, "Error: capture failed\n");
        wim_ctx_free(&ctx);
        return ret;
    }

    if (g_boot)
        ctx.header.boot_index = (uint32_t)ctx.image_count;

    ret = wim_finalize(&ctx, g_check);
    if (ret != 0) {
        fprintf(stderr, "Error: finalize failed\n");
        wim_ctx_free(&ctx);
        return ret;
    }

    printf("Done.\n");
    wim_ctx_free(&ctx);
    return 0;
}

static int do_apply(void)
{
    WimCtx ctx;
    wim_ctx_init(&ctx);

    int ret = wim_open(&ctx, g_wim_path);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to open \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    int idx = g_image_index ? g_image_index : 1;
    if (idx < 1 || idx > (int)ctx.image_count) {
        fprintf(stderr, "Error: image index %d out of range (1-%d)\n",
                idx, (int)ctx.image_count);
        wim_ctx_free(&ctx);
        return 1;
    }

    ret = wim_select_image(&ctx, idx);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to select image %d\n", idx);
        wim_ctx_free(&ctx);
        return ret;
    }

    const char* img_name = "";
    if (ctx.image_infos && (idx - 1) < (int)ctx.image_info_count)
        img_name = ctx.image_infos[idx - 1].name;

    printf("Applying image %d (\"%s\") to \"%s\"\n",
           idx, img_name, g_source_or_target);

    const WimDentry* root = wim_get_root(&ctx, idx);
    if (!root) {
        fprintf(stderr, "Error: failed to get root dentry for image %d\n", idx);
        wim_ctx_free(&ctx);
        return 1;
    }

    ret = wim_extract_tree(&ctx, root, g_source_or_target);
    if (ret != 0) {
        fprintf(stderr, "Error: extraction failed\n");
        wim_ctx_free(&ctx);
        return ret;
    }

    printf("Done applying WIM image.\n");

    if (g_check) {
        printf("Verifying integrity of \"%s\"...\n", g_wim_path);
        ret = wim_verify_integrity(&ctx);
        if (ret != 0) {
            fprintf(stderr, "Error: integrity verification failed\n");
            wim_ctx_free(&ctx);
            return ret;
        }
        printf("Integrity OK.\n");
    }

    wim_ctx_free(&ctx);
    return 0;
}

static int do_append(void)
{
    fprintf(stderr, "Error: append not yet implemented\n");
    return 1;
}

static int do_delete(void)
{
    fprintf(stderr, "Error: delete not yet implemented\n");
    return 1;
}

static int do_info(void)
{
    WimCtx ctx;
    wim_ctx_init(&ctx);

    int ret = wim_open(&ctx, g_wim_path);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to open \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    /* WIM-level info */
    print_wim_info(&ctx);

    /* Optional sections */
    if (g_show_header)
        print_header_info(&ctx.header);

    if (g_show_xml) {
        printf("\nXML data:\n");
        const char* xml = wim_get_xml(&ctx);
        printf("%s\n", xml ? xml : "");
    }

    if (g_show_blobs)
        print_blob_info(ctx.blobs, ctx.blob_count);

    /* If a specific image was requested, show only that one */
    int start = 0, end = (int)ctx.image_info_count;
    if (g_image_index > 0) {
        if (g_image_index > (int)ctx.image_info_count) {
            fprintf(stderr, "Error: image %d out of range (1-%d)\n",
                    g_image_index, (int)ctx.image_info_count);
            wim_ctx_free(&ctx);
            return 1;
        }
        start = g_image_index - 1;
        end = g_image_index;
    }

    /* Per-image info */
    printf("\n");
    for (int i = start; i < end; i++) {
        const WimImageInfo* info = &ctx.image_infos[i];
        printf("Index:                  %d\n", i + 1);
        printf("Name:                   %s\n", info->name);
        if (info->description[0])
            printf("Description:            %s\n", info->description);
        printf("Directory Count:        %u\n", info->dir_count);
        printf("File Count:             %u\n", info->file_count);
        printf("Total Bytes:            %llu\n", (unsigned long long)info->total_bytes);
        if (info->creation_time) {
            char* ts = filetime_to_string(info->creation_time);
            printf("Creation Time:          %s\n", ts);
            free(ts);
        }
        if (info->modification_time) {
            char* ts = filetime_to_string(info->modification_time);
            printf("Last Modification Time: %s\n", ts);
            free(ts);
        }
        printf("\n");
    }

    wim_ctx_free(&ctx);
    return 0;
}

static int do_dir(void)
{
    WimCtx ctx;
    wim_ctx_init(&ctx);

    int ret = wim_open(&ctx, g_wim_path);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to open \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    int idx = g_image_index ? g_image_index : 1;
    if (idx < 1 || idx > (int)ctx.image_count) {
        fprintf(stderr, "Error: image index %d out of range (1-%d)\n",
                idx, (int)ctx.image_count);
        wim_ctx_free(&ctx);
        return 1;
    }

    ret = wim_select_image(&ctx, idx);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to select image %d\n", idx);
        wim_ctx_free(&ctx);
        return ret;
    }

    const WimDentry* root = wim_get_root(&ctx, idx);
    if (!root) {
        fprintf(stderr, "Error: failed to get root dentry for image %d\n", idx);
        wim_ctx_free(&ctx);
        return 1;
    }

    print_dentry_tree(root, "", g_detailed);

    wim_ctx_free(&ctx);
    return 0;
}

static const WimDentry* find_child_by_name(const WimDentry* parent, const char* name)
{
    for (size_t i = 0; i < parent->child_count; i++) {
        if (strcmp(parent->children[i].name_utf8, name) == 0)
            return &parent->children[i];
    }
    return NULL;
}

static int do_extract(void)
{
    WimCtx ctx;
    wim_ctx_init(&ctx);

    int ret = wim_open(&ctx, g_wim_path);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to open \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    int idx = g_image_index;
    if (idx < 1 || idx > (int)ctx.image_count) {
        fprintf(stderr, "Error: image index %d out of range (1-%d)\n",
                idx, (int)ctx.image_count);
        wim_ctx_free(&ctx);
        return 1;
    }

    ret = wim_select_image(&ctx, idx);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to select image %d\n", idx);
        wim_ctx_free(&ctx);
        return ret;
    }

    const WimDentry* root = wim_get_root(&ctx, idx);
    if (!root) {
        fprintf(stderr, "Error: failed to get root dentry for image %d\n", idx);
        wim_ctx_free(&ctx);
        return 1;
    }

    /* Determine destination */
    const char* dest = g_dest_dir[0] ? g_dest_dir : ".";

    if (g_extract_path_count == 0) {
        /* Extract everything */
        ret = wim_extract_tree(&ctx, root, dest);
    } else {
        /* Extract specific paths */
        for (int i = 0; i < g_extract_path_count; i++) {
            printf("Extracting \"%s\"...\n", g_extract_paths[i]);

            /* Strip leading slashes */
            const char* path = g_extract_paths[i];
            while (*path == '/') path++;

            const WimDentry* cur = root;
            int found = 1;

            if (*path) {
                /* Walk path components */
                char pathbuf[4096];
                snprintf(pathbuf, sizeof(pathbuf), "%s", path);
                char* saveptr = NULL;
                char* comp = strtok_r(pathbuf, "/", &saveptr);
                while (comp && cur) {
                    const WimDentry* child = find_child_by_name(cur, comp);
                    if (!child) {
                        fprintf(stderr, "Error: path \"%s\" not found in image\n",
                                g_extract_paths[i]);
                        found = 0;
                        cur = NULL;
                        break;
                    }
                    cur = child;
                    comp = strtok_r(NULL, "/", &saveptr);
                }
            }

            if (!found) { ret = 1; continue; }

            if (cur) {
                if (cur->attributes & WIM_FILE_ATTRIBUTE_DIRECTORY) {
                    ret = wim_extract_tree(&ctx, cur, dest);
                } else {
                    char dest_path[8192];
                    snprintf(dest_path, sizeof(dest_path), "%s/%s", dest, cur->name_utf8);
                    ret = wim_extract_tree(&ctx, cur, dest);
                }
                if (ret != 0) break;
            }
        }
    }

    if (ret == 0) printf("Done.\n");
    wim_ctx_free(&ctx);
    return ret;
}

static int do_verify(void)
{
    WimCtx ctx;
    wim_ctx_init(&ctx);

    int ret = wim_open(&ctx, g_wim_path);
    if (ret != 0) {
        fprintf(stderr, "Error: failed to open \"%s\"\n", g_wim_path);
        wim_ctx_free(&ctx);
        return ret;
    }

    printf("Verifying integrity of \"%s\"...\n", g_wim_path);
    ret = wim_verify_integrity(&ctx);
    if (ret == 0)
        printf("Verification successful.\n");
    else
        printf("Verification FAILED.\n");

    wim_ctx_free(&ctx);
    return ret;
}

/* ---- main ---- */

int main(int argc, char* argv[])
{
    /* Initialize defaults */
    memset(g_wim_path, 0, sizeof(g_wim_path));
    memset(g_source_or_target, 0, sizeof(g_source_or_target));
    memset(g_image_name, 0, sizeof(g_image_name));
    memset(g_image_desc, 0, sizeof(g_image_desc));
    g_image_index = 0;
    g_boot = 0;
    g_check = 0;
    g_show_header = 0;
    g_show_xml = 0;
    g_show_blobs = 0;
    g_detailed = 0;
    snprintf(g_compress, sizeof(g_compress), "xpress");
    memset(g_path_filter, 0, sizeof(g_path_filter));
    memset(g_dest_dir, 0, sizeof(g_dest_dir));
    g_extract_path_count = 0;

    if (!parse_args(argc, argv))
        return 1;

    int ret;
    switch (g_cmd) {
    case CMD_CAPTURE:  ret = do_capture(); break;
    case CMD_APPLY:    ret = do_apply(); break;
    case CMD_APPEND:   ret = do_append(); break;
    case CMD_DELETE:    ret = do_delete(); break;
    case CMD_INFO:     ret = do_info(); break;
    case CMD_DIR:      ret = do_dir(); break;
    case CMD_EXTRACT:  ret = do_extract(); break;
    case CMD_VERIFY:   ret = do_verify(); break;
    default:
        print_usage();
        ret = 1;
        break;
    }

    /* Free extract paths */
    for (int i = 0; i < g_extract_path_count; i++)
        free(g_extract_paths[i]);

    return ret;
}
