$if (_NTDDK_)

#define PTI_SHIFT  12L
#define PDI_SHIFT  21L
#define PPI_SHIFT  30L
#define PXI_SHIFT  39L
#define PTE_PER_PAGE 512
#define PDE_PER_PAGE 512
#define PPE_PER_PAGE 512
#define PXE_PER_PAGE 512
#define PTI_MASK_ARM64 (PTE_PER_PAGE - 1)
#define PDI_MASK_ARM64 (PDE_PER_PAGE - 1)
#define PPI_MASK       (PPE_PER_PAGE - 1)
#define PXI_MASK       (PXE_PER_PAGE - 1)

#define PXE_BASE    0xFFFFE4F2793C9000ULL
#define PXE_SELFMAP 0xFFFFE4F2793C9E48ULL
#define PPE_BASE    0xFFFFE4F279200000ULL
#define PDE_BASE    0xFFFFE4F240000000ULL
#define PTE_BASE    0xFFFFE48000000000ULL
#define PXE_TOP     0xFFFFE4F2793C9FFFULL
#define PPE_TOP     0xFFFFE4F2793FFFFFULL
#define PDE_TOP     0xFFFFE4F27FFFFFFFULL
#define PTE_TOP     0xFFFFE4FFFFFFFFFFULL

extern NTKERNELAPI PVOID MmHighestUserAddress;
extern NTKERNELAPI PVOID MmSystemRangeStart;
extern NTKERNELAPI ULONG64 MmUserProbeAddress;

#define MM_HIGHEST_USER_ADDRESS MmHighestUserAddress
#define MM_SYSTEM_RANGE_START   MmSystemRangeStart
#if defined(_LOCAL_COPY_USER_PROBE_ADDRESS_)
#define MM_USER_PROBE_ADDRESS _LOCAL_COPY_USER_PROBE_ADDRESS_
extern ULONG64 _LOCAL_COPY_USER_PROBE_ADDRESS_;
#else
#define MM_USER_PROBE_ADDRESS MmUserProbeAddress
#endif
#define MM_LOWEST_USER_ADDRESS   (PVOID)0x10000
#define MM_LOWEST_SYSTEM_ADDRESS (PVOID)0xFFFF000000000000ULL

$endif /* _NTDDK_ */
