@ stdcall WskCaptureProviderNPI(ptr long ptr)
@ stdcall WskDeregister(ptr)
@ stdcall WskRegister(ptr ptr)
@ stdcall WskReleaseProviderNPI(ptr)

; Network Module Registrar (NMR) stubs — dev-nt6-1 branch
@ stdcall NmrRegisterClient(ptr ptr ptr)
@ stdcall NmrDeregisterClient(ptr)
@ stdcall NmrWaitForClientDeregisterComplete(ptr)
@ stdcall NmrRegisterProvider(ptr ptr ptr)
@ stdcall NmrDeregisterProvider(ptr)
@ stdcall NmrWaitForProviderDeregisterComplete(ptr)
@ stdcall NmrClientAttachProvider(ptr ptr ptr ptr ptr)
@ stdcall NmrClientDetachProviderComplete(ptr)
@ stdcall NmrProviderDetachClientComplete(ptr)

; Windows Filtering Platform (WFP) kernel stubs — dev-nt6-1 branch
@ stdcall FwpsCalloutRegister0(ptr ptr ptr)
@ stdcall FwpsCalloutUnregisterById0(long)
@ stdcall FwpsCalloutUnregisterByKey0(ptr)
@ stdcall FwpsAllocateCloneNetBufferList0(ptr ptr ptr long ptr)
@ stdcall FwpsFreeCloneNetBufferList0(ptr long)
@ stdcall FwpsAllocateNetBufferAndNetBufferList0(ptr long long ptr long double ptr)
@ stdcall FwpsInjectNetworkSendAsync0(ptr ptr long long ptr ptr ptr)
@ stdcall FwpsInjectNetworkReceiveAsync0(ptr ptr long long long long ptr ptr ptr)
@ stdcall FwpsInjectionHandleCreate0(long long ptr)
@ stdcall FwpsInjectionHandleDestroy0(ptr)
@ stdcall FwpsNetBufferListRelease0(ptr)
@ stdcall FwpmEngineOpen0(ptr long ptr ptr ptr)
@ stdcall FwpmEngineClose0(ptr)
@ stdcall FwpmTransactionBegin0(ptr long)
@ stdcall FwpmTransactionCommit0(ptr)
@ stdcall FwpmTransactionAbort0(ptr)
@ stdcall FwpmFilterAdd0(ptr ptr ptr ptr)
@ stdcall FwpmFilterDeleteByKey0(ptr ptr)
@ stdcall FwpmFilterDeleteById0(ptr double)
@ stdcall FwpmFilterGetByKey0(ptr ptr ptr)
@ stdcall FwpmFilterGetById0(ptr double ptr)
@ stdcall FwpmCalloutAdd0(ptr ptr ptr ptr)
@ stdcall FwpmCalloutDeleteByKey0(ptr ptr)
@ stdcall FwpmCalloutDeleteById0(ptr long)
@ stdcall FwpmProviderAdd0(ptr ptr ptr)
@ stdcall FwpmProviderDeleteByKey0(ptr ptr)
@ stdcall FwpmFreeMemory0(ptr)
